### PR TITLE
Mimica outputs for part 2 and part 2 optional

### PR DESCRIPTION
**Pull request by AlejandroBaroPerez**

### CODE REVIEW

**Comment by twjuliano** [comment]
Hi @AlejandroBaroPerez, could you please remove `notebooks/setup/aerosol-specification.ipynb` from the commit? Thanks!

**Comment by AlejandroBaroPerez** [comment]
Hi @twjuliano, I created a new commit (4168aae) in which  I removed "notebooks/setup/aerosol-specification.ipynb" . Are you able to see this in the pull request?

**Comment by twjuliano** [comment]
@AlejandroBaroPerez Yes, I see the commit. However, it looks like the you removed the file from the folder structure. We need to keep the file there but just remove it from the commit. Basically, when you `git add` files to prepare for your commit, include only the ones related to MIMICA. I would do it on my end except it won't let me.

**Comment by AlejandroBaroPerez** [comment]
@twjuliano, Ok I understand now what you say, but  I am confused because (before removing the file in the last commit) I didn't commit changes in "notebooks/setup/aerosol-specification.ipynb". I only added the MIMICA outputs. I just checked again commit 8516523 (above) and I see that MIMICA  outputs are the only modified files. Am I missing something?

**Comment by twjuliano** [comment]
@AlejandroBaroPerez Interesting, yes I see that commit `8516523` includes only your three files. For some reason, when the PR came up, there was also the additional file in there with some changes. Can you try to revert back to commit `8516523`? Let's see what that looks like. Thanks for your patience!

**Comment by AlejandroBaroPerez** [comment]
@twjuliano  No worries :)  I just removed the last commit. Let's see what happens now. If the issue is present again then I will pull from main, merge with my branch and push again.

**Comment by twjuliano** [comment]
@AlejandroBaroPerez Somehow it still shows the other file, but I think it's not a big deal. I'll go ahead and approve and if there is an issue with the Notebook file, then I'll fix it. Thanks again!

**Review by twjuliano — APPROVED** [review]

**Pull request merged**
