### PR TITLE
scale-sdm 

### PR DESCRIPTION
**Pull request by anuiitd**
It includes tIme series and 2D data using scale-sdm.

### CODE REVIEW

**Comment by twjuliano** [comment]
@anuiitd Thank you for your submission! It looks like one file contains time series info, another is time-height, and the last is 3D. Is that correct? If so, we're asking folks to put the following variables into different files according to the variable list [here](https://docs.google.com/spreadsheets/d/1Vl8jYGviet7EtXZuQiitrx4NSkV1x27aJAhxxjBb9zI/edit?gid=1756539842#gid=1756539842):
1. time series and time-height into one file
2. 2D into one file 
3. 3D into one file

File naming conventions should indicate the experiment type, [following this page](https://arm-development.github.io/comble-mip/timeline.html).

Also note that 2D and 3D files will be uploaded to a separate area. I hope you received the email I sent out the other day containing submission instructions (subject line 'Submitting 2D and 3D files for COMBLE-MIP'), but please let me know if not.

Hope this info helps. Many thanks again for your efforts!

Tim

**Comment by anuiitd** [comment]
@twjuliano Thank you for notifying it.
I have modified the file in one file based on the file naming conventions.

**Review by twjuliano — APPROVED** [review]

**Comment by twjuliano** [comment]
@anuiitd it looks like the pa variable [time,height] is missing from your files. This is a necessary variable for the plotting scripts. Could you please double check the list of requested variables and make sure that you're reporting at least all of the ones in green? Thank you!

**Comment by anuiitd** [comment]
@twjuliano I included the variable pa. However, we do not have some green ones like obukhov length and number concentration of aerosols in the current simulation.

**Pull request merged**
