### PR TITLE
The first UCLALES-SALSA results

### PR DESCRIPTION
**Pull request by TomiRaatikainen**
The first UCLALES-SALSA results for Part I can be found from output_les/uclales-salsa/sandbox/. These were calculated using notebook convert_UCLALES-SALSA_output_to_dephy_format.ipynb from notebooks/conversion_output/. Model inputs were generated using notebook convert_comble_dephy_forcing_to_UCLALES-SALSA_forcing.ipynb  from notebooks/conversion/. Model inputs or the raw output data are not included.

### CODE REVIEW

**Review by twjuliano — APPROVED** [review]

**Comment by twjuliano** [comment]
@TomiRaatikainen It looks like the 'FixN' and 'FixN_def_z0' files don't contain 2D information through the end of the simulation. Feel free to submit another PR that includes those fields. Thanks.

**Comment by TomiRaatikainen** [comment]
> @TomiRaatikainen It looks like the 'FixN' and 'FixN_def_z0' files don't contain 2D information through the end of the simulation. Feel free to submit another PR that includes those fields. Thanks.

I looked at the files and the data seemed to be there. However, the output model time varies depending on the CFL condition. In practice, the model time may exceed the target time by 1 s (the maximum time step). The plotting script (check_les.ipynb) uses condition df = df[round(df.time) == times[tt]*3600.], which means that the maximum difference is 0.5 s. The simplest fix to the problem is to change the condition to df = df[abs(round(df.time)-times[tt]*3600.)<2.]. Would this be enough for now? I can also update the data.

**Comment by fridlind** [comment]
@TomiRaatikainen Yes, understood, our model does this, too. What I do is report the nearest appropriate value on the requested output time frequency, which is for all practical purposes very close as in your explanation above. If you don't mind updating your times to be precisely the requested frequency, just to simplify things on our end, that would be much appreciated, but yes, we can work with this. 

@floriantornow Can you please relax the check_les.ipynb rounding threshold as suggested above, in any case?

Many thanks all around!

**Comment by floriantornow** [comment]
@fridlind @twjuliano Yes, done! Thank you for the suggestion, @TomiRaatikainen ! I changed the function as suggested.

**Comment by twjuliano** [comment]
> @fridlind @twjuliano Yes, done! Thank you for the suggestion, @TomiRaatikainen ! I changed the function as suggested.

Thanks all! @floriantornow @fridlind @TomiRaatikainen

**Pull request merged**
